# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 30a77c24c44baecde12119f1baa434fc2d79036d1fe94bbb1d16c0c5a3f6be102ecb421bd36a1362f2d7a5289b107dac74d200319afc121b706606c591f9150a

test:
  secret_key_base: 7b1efa064d30f7559565be3f84f484eb269152f3ed682fc7111cba55a48a59e1e54415f81a82f5d781ce91e267c183a1d8f8d6cfac7d740755737d8632e2614f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
